[package]
name = "nvim"
version = "0.1.0"
authors = ["vold-dev <matt@vole.dev>"]
edition = "2018"
build="build.rs"

[dependencies]
libc = "0.2.0"
bitflags = "1.2"
byte-strings = "0.1.3"

[dependencies.xdiff]
path = "rust-deps/xdiff"

[build-dependencies.cmake]
path = "rust-deps/cmake"
